config/routes.rb
Tumitfahrer::Application.routes.draw do

  namespace :api do
    namespace :v2, :defaults => { :format => 'json' } do
      match '/activities/badges', to: 'activities#get_badge_counter', via: :get
      resources :activities
      resource :forgot
      resource :search
      resource :feedback
      resources :users do
        resources :devices
        resources :ratings
        match '/requests', to: 'requests#get_user_requests', via: :get
        match '/rides', to: 'rides#get_user_rides', via: :get
        resources :rides do
          resources :requests
        end
      end
      match '/rides/ids', to: 'rides#get_ids_existing_rides', via: :get
      resources :rides do
        resources :requests
        resources :conversations do
          resources :messages do
          end
        end
      end
      resource :sessions
    end
  end

  resources :users
  resources :rides
  resource :sessions, only: [:new, :create, :destroy]

  root "static_pages#home"
  match "/signup", to: "users#new", via: 'get'
  match "/signin", to: "sessions#new", via: 'get'
  match "/signout", to: "sessions#destroy", via: 'delete'
  match "/help", to: "static_pages#help", via: 'get'
  match "/contact", to: "static_pages#contact", via: 'get'
  match "/about", to: "static_pages#about", via: 'get'
  match "/discover", to: "static_pages#discover", via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about

  end

  def contact

  end

  def contact_us
    UserMailer.contact_email(params[:Email], params[:Name], params[:Title], params[:Message]).deliver
    flash[:success] = "Your message has been sent successfully"
    redirect_to root_path
  end

  def team

  end
  def privacy

  end

  def terms

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About Us") %>

<h1>About TUMitfahrer</h1>
<p>TUMitfahrer was created by students for students.</p>

app/views/static_pages/contact.html.erb
<%= javascript_include_tag "jquery.bootpag.min.js" %>

<div class="container_ride">
  <% provide(:title, "Contact") %>
  <div class="row"  id="main_img" style="padding-left:74px;margin-top: 10px; background: url('<%= asset_path "1.jpg"%>')">

    <div class="col-xs-9 col-md-9 " style="width:96%;margin-top:25px;">
      <div class="panel panel-primary"style="border: none;border-radius: 0px;margin-top:40px;margin-bottom:50px;">
        <div class="panel-heading" style="border: none;border-radius: 0px;background: #2F2F2F;color: #beddf1;">
          <h3 class="panel-title " style="height: 22px;margin-top: 2px;margin-left: 14px">&nbsp;&nbsp; Contact</h3>

        </div>
      </div>
      <div class="panel-body" class="form-horizontal"style="background-color:lightgrey;">
        <div class="form-group">
    <%= form_tag('/contact_us', method: :post) do %>
      Name    <%= text_field_tag 'Name' %>
      Email   <%= text_field_tag 'Email' %>
      Title   <%= text_field_tag 'Title' %>
      Message <%= text_field_tag 'Message' %>
              <input name="commit" type="submit" value="Send" />
        <% end %>
    </div>
      </div>
    </div>

  </div>
</div>

app/views/static_pages/discover.html.erb
<% provide(:title, "Discover") %>
<h1>Discovering great places - coming soon!</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<p>TUMitfahrer is a car sharing platform for students.
It lets you:
<ol>
  <li>Drive to the campus</li>
  <li>Discover new places</li>
  <li>Meet other students</li>
</ol></p>

app/views/static_pages/home.html.erb
<div class="center main-section jumbo">
  <h1>TUMitfahrer</h1>

  <p>Car sharing platform for students</p>

  <table class="table table-borderless">
    <tbody>
    <tr>
      <td><%= link_to image_tag("uni_icon.png", height: '170', width: '170', alt: "Drive to Uni"), '#' %></td>
      <td><%= link_to image_tag("adventure_icon.png", height: '170', width: '170', alt: "Drive for weekend trips"), '#' %></td>
      <td><%= link_to image_tag("friends_icon.png", height: '170', width: '170', alt: "Meet other students"), '#' %></td>
    </tr>
    <tr>
      <td>Drive to Uni</td>
      <td>Drive for weekend trips</td>
      <td>Meet other students</td>
    </tr>
    </tbody>
  </table>
  <% if signed_in? %>
      <%= link_to 'See all rides!', rides_path, class: "btn btn-xlarge btn-primary" %>
  <% else %>
      <%= link_to 'Sign up now!', signup_path, class: "btn btn-xlarge btn-primary" %>
  <% end %>
</div>

<div class="even-section center">
  <h2>How does it work?</h2>
  <iframe src="//player.vimeo.com/video/58241549" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>

<div class="odd-section center">
  <h2>Download mobile app </h2>

  <%= link_to image_tag("App_Store.png", height: '60', width: '170', alt: "App Store"), '#' %>
  <%= link_to image_tag("Play_Store.png", height: '60', width: '170', alt: "Play Store"), '#' %>

</div>

app/views/static_pages/privacy.html.erb
<div class="container_main">
  <% provide(:title, "Privacy Statement") %>

  <div class="row new_ride_background main_div" id="main_img" style="background: url('<%= asset_path "1.jpg"%>')  no-repeat center center fixed">
    <div class="ride_new_page_background">
      <div class="row">
        <div class="col-xs-1 col-md-3">
        </div>
        <div class="col-xs-10 col-md-6 ride_new_form" >
          <div class="panel panel-primary" style="width: 100%; border: none;">
            <div class="panel-heading ride_new_heading" style="background: black; border-color: black;">
              <h3 class="panel-title" style="color: #f2f2f2;"><%= t("static.privacy") %></h3>
            </div>
            <div class="panel-body panel_body_background" style="height: 400px">
              <div class="row">
                <div class="col-xs-12 col-md-12">
                  <b><%= t("static.privacy_general") %></b>
                  <p align="justify" class="privacy_p"><%= t("static.privacy_general_desc") %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-1 col-md-3"></div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/team.html.erb
<div class="container_main">
  <% provide(:title, "Team") %>

  <div class="row new_ride_background main_div" id="main_img" style="background: url('<%= asset_path "MainCampusOrigin.png"%>')  no-repeat center center fixed">
    <div class="ride_new_page_background">
      <div class="row">
        <div class="col-xs-1 col-md-3">
        </div>
        <div class="col-xs-10 col-md-6 ride_new_form" >
          <div class="panel panel-primary" style="width: 100%; border: none;">
            <div class="panel-heading ride_new_heading" style="background: black; border-color: black;">
              <h3 class="panel-title" style="color: #f2f2f2;"><%= t("static.team") %></h3>
            </div>
            <div class="panel-body panel_body_background">
              <div class="row" style="border-bottom: 1px solid black; padding-bottom: 14px;">
                <div class="col-xs-3 col-md-3">
                  <img src="<%= asset_path "MichaelPhoto@2x.jpg" %>" class="img-responsive">
                </div>
                <div class="col-xs-9 col-md-9">
                  <h4 style="color: #005c91; margin-top: -3px; margin-bottom: 0px;">Michael Schermann</h4>
                  <b>Creative Director</b>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">When in danger, when in doubt, run in circles, scream, and shout</p>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">TUMitfahrer is an awesome project because the teams grew together on an innovative project. TUMitfahrer enabled the students to pursue their ideas while fulfilling their study requirements.</p>
                </div>
              </div>
              <div class="row" style="border-bottom: 1px solid black; padding-bottom: 14px; padding-top: 14px;">
                <div class="col-xs-3 col-md-3">
                  <img src="<%= asset_path "PawelPhoto@2x.jpg" %>" class="img-responsive">
                </div>
                <div class="col-xs-9 col-md-9">
                  <h4 style="color: #005c91; margin-top: -3px; margin-bottom: 0px;">Pawel Kwiecien</h4>
                  <b>iOS and backend developer</b>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">Life begins at the end of your comfort zone</p>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">TUMitfahrer was for me the final project for my Master Thesis. I developed complete iOS application and backend using Ruby on Rails. My research included innovative product development processes.</p>
                </div>
              </div>
              <div class="row" style="border-bottom: 1px solid black; padding-bottom: 14px; padding-top: 14px;">
                <div class="col-xs-3 col-md-3">
                  <img src="<%= asset_path "LukasPhoto@2x.jpg" %>" class="img-responsive">
                </div>
                <div class="col-xs-9 col-md-9">
                  <h4 style="color: #005c91; margin-top: -3px; margin-bottom: 0px;">Lukasz Kwiatkowski</h4>
                  <b>UI/UX Designer, Photography, Marketing</b>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">Creativity is doing something out of nothing</p>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">I took this project as my IDP. Personally i enjoyed that project because i could use my slightly artistic background in real application, to design something which students could enjoy.</p>
                </div>
              </div>
              <div class="row" style="border-bottom: 1px solid black; padding-bottom: 14px; padding-top: 14px;">
                <div class="col-xs-3 col-md-3">
                  <img src="<%= asset_path "ShahidPhoto@2x.jpg" %>" class="img-responsive">
                </div>
                <div class="col-xs-9 col-md-9">
                  <h4 style="color: #005c91; margin-top: -3px; margin-bottom: 0px;">Muhammad Shahid Aslam</h4>
                  <b>Backend and Web application Developer</b>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">Failure is not an option, it comes bundled with the software</p>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">I took this project as IDP. I learned new things like how to use websockets for chat and how to develop responsive web application.</p>
                </div>
              </div>
              <div class="row" style="border-bottom: 1px solid black; padding-bottom: 14px; padding-top: 14px;">
                <div class="col-xs-3 col-md-3">
                  <img src="<%= asset_path "AnuradaPhoto@2x.jpg" %>" class="img-responsive">
                </div>
                <div class="col-xs-9 col-md-9">
                  <h4 style="color: #005c91; margin-top: -3px; margin-bottom: 0px;">Anuradha</h4>
                  <b>Web application developer</b>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">Ruby is better than diamond</p>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">I took this project as my IDP and it is an awesome experience and opportunity to learn new language like Ruby on Rails.</p>
                </div>
              </div>
              <div class="row" style="border-bottom: 1px solid black; padding-bottom: 14px; padding-top: 14px;">
                <div class="col-xs-3 col-md-3">
                  <img src="<%= asset_path "BehrozPhoto@2x.jpg" %>" class="img-responsive">
                </div>
                <div class="col-xs-9 col-md-9">
                  <h4 style="color: #005c91; margin-top: -3px; margin-bottom: 0px;">Behroz Sikander</h4>
                  <b>Backend / VisioM developer</b>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">After this project, I like Ruby more than Natalie Portman.</p>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">TUMitfahrer was an awesome project that gave me the chance to work on multiple platforms. I learnt ROR, Android, iPhone, Java and C++ in a single project.</p>
                </div>
              </div>
              <div class="row" style="border-bottom: 1px solid black; padding-bottom: 14px; padding-top: 14px;">
                <div class="col-xs-3 col-md-3">
                  <img src="<%= asset_path "SaqibPhoto@2x.jpg" %>" class="img-responsive">
                </div>
                <div class="col-xs-9 col-md-9">
                  <h4 style="color: #005c91; margin-top: -3px; margin-bottom: 0px;">Hafiz Saqib Javed</h4>
                  <b>Notification Engine/Pebble smartwatch developer</b>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">Whaa! you didn’t get notification??? Probably thunder in the cloud.</p>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">Getting an opportunity to work on a real time project with collaborative environment and multiple technologies, couldn’t get anything better. I took it as an IDP and really enjoyed working on Pebble and RoR.</p>
                </div>
              </div>
              <div class="row" style="border-bottom: 1px solid black; padding-bottom: 14px; padding-top: 14px;">
                <div class="col-xs-3 col-md-3">
                  <img src="<%= asset_path "AmrPhoto@2x.jpg" %>" class="img-responsive">
                </div>
                <div class="col-xs-9 col-md-9">
                  <h4 style="color: #005c91; margin-top: -3px; margin-bottom: 0px;">Amr Arafat</h4>
                  <b>Android Developer</b>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">It’s not a Bug, It’s a feature *evil smile*</p>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">TUMitfahrer is an exciting project.  I learned a lot of stuff and had a lot of fun. I was on the Android team and I really enjoyed working on the project.</p>
                </div>
              </div>
              <div class="row" style="border-bottom: 1px solid black; padding-bottom: 14px; padding-top: 14px;">
                <div class="col-xs-3 col-md-3">
                  <img src="<%= asset_path "AbiPhoto@2x.jpg" %>" class="img-responsive">
                </div>
                <div class="col-xs-9 col-md-9">
                  <h4 style="color: #005c91; margin-top: -3px; margin-bottom: 0px;">Abhijith Srivatsav</h4>
                  <b>Android developer</b>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">There is no spoon</p>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">TUMitfahrer is my IDP, for which I’m responsible for the Android application. I’m the resident Android evangelist and the go-to guy for everything Android. I particularly like this project as it affords me the opportunity to exercise my skills and experiment with application building techniques.</p>
                </div>
              </div>
              <div class="row" style="border-bottom: 1px solid black; padding-bottom: 14px; padding-top: 14px;">
                <div class="col-xs-3 col-md-3">
                  <img src="<%= asset_path "DansenPhoto@2x.jpg" %>" class="img-responsive">
                </div>
                <div class="col-xs-9 col-md-9">
                  <h4 style="color: #005c91; margin-top: -3px; margin-bottom: 0px;">Dansen Zhou</h4>
                  <b> iOS, Android, Web application tester</b>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">Test is a procedure of making everything ruined and starting beauty </p>
                  <p style="line-height: 1em; font-size: 0.9em;" align="justify">I took this project as my IDP. In this awesome project, I take charge of all the tests including unit test, ui automatic test, integration test, etc. It is both excited and painful to join all the different platforms with different environments, different programme languages.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-1 col-md-3"></div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/terms.html.erb
<div class="container_main">
  <% provide(:title, "Terms and Conditions") %>

  <div class="row new_ride_background main_div" id="main_img" style="background: url('<%= asset_path "1.jpg"%>')  no-repeat center center fixed">
    <div class="ride_new_page_background">
      <div class="row">
        <div class="col-xs-1 col-md-3">
        </div>
        <div class="col-xs-10 col-md-6 ride_new_form" >
          <div class="panel panel-primary" style="width: 100%; border: none;">
            <div class="panel-heading ride_new_heading" style="background: black; border-color: black;">
              <h3 class="panel-title" style="color: #f2f2f2;"><%= t("static.terms") %></h3>
            </div>
            <div class="panel-body panel_body_background">
              <div class="row">
                <div class="col-xs-12 col-md-12">
                  <b><%= t("static.terms_scope") %></b>
                  <p align="justify" class="privacy_p"><%= t("static.terms_scope_1") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_scope_2") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_scope_3") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_scope_4") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_scope_5") %></p>
                  <b><%= t("static.terms_content") %></b>
                  <p align="justify" class="privacy_p"><%= t("static.terms_content_1") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_content_2") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_content_3") %></p>
                  <b><%= t("static.terms_obligations") %></b>
                  <p align="justify" class="privacy_p"><%= t("static.terms_obligations_1") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_obligations_2") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_obligations_3") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_obligations_4") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_obligations_5") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_obligations_6") %></p>
                  <b><%= t("static.terms_collection") %></b>
                  <p align="justify" class="privacy_p"><%= t("static.terms_collection_1") %></p>
                  <b><%= t("static.terms_rating") %></b>
                  <p align="justify" class="privacy_p"><%= t("static.terms_rating_1") %></p>
                  <b><%= t("static.terms_right") %></b>
                  <p align="justify" class="privacy_p"><%= t("static.terms_right_1") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_right_2") %></p>
                  <b><%= t("static.terms_termination") %></b>
                  <p align="justify" class="privacy_p"><%= t("static.terms_termination_1") %></p>
                  <b><%= t("static.terms_liability") %></b>
                  <p align="justify" class="privacy_p"><%= t("static.terms_liability_1") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_liability_2") %></p>
                  <p align="justify" class="privacy_p"><%= t("static.terms_liability_3") %></p>
                  <b><%= t("static.terms_jurisdiction") %></b>
                  <p align="justify" class="privacy_p"><%= t("static.terms_jurisdiction_1") %></p>
                  <b><%= t("static.terms_change") %></b>
                  <p align="justify" class="privacy_p"><%= t("static.terms_change_1") %></p>

              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-1 col-md-3"></div>
      </div>
    </div>
  </div>
</div>
</div>