config/routes.rb
Tumitfahrer::Application.routes.draw do

  namespace :api do
    namespace :v2, :defaults => { :format => 'json' } do
      match '/activities/badges', to: 'activities#get_badge_counter', via: :get
      resources :activities
      resource :forgot
      resource :search
      resource :feedback
      resources :users do
        resources :devices
        resources :ratings
        match '/requests', to: 'requests#get_user_requests', via: :get
        match '/rides', to: 'rides#get_user_rides', via: :get
        resources :rides do
          resources :requests
        end
      end
      match '/rides/ids', to: 'rides#get_ids_existing_rides', via: :get
      resources :rides do
        resources :requests
        resources :conversations do
          resources :messages do
          end
        end
      end
      resource :sessions
    end
  end

  resources :users
  resources :rides
  resource :sessions, only: [:new, :create, :destroy]

  root "static_pages#home"
  match "/signup", to: "users#new", via: 'get'
  match "/signin", to: "sessions#new", via: 'get'
  match "/signout", to: "sessions#destroy", via: 'delete'
  match "/help", to: "static_pages#help", via: 'get'
  match "/contact", to: "static_pages#contact", via: 'get'
  match "/about", to: "static_pages#about", via: 'get'
  match "/discover", to: "static_pages#discover", via: 'get'

end

app/views/layouts/_footer.html.erb
<!--<footer class="footer">-->
  <!--<nav>-->
    <!--<ul>-->
      <!--<li><%#= link_to 'About', about_path %></li>-->
      <!--<li><%#= link_to 'Help', help_path %></li>-->
      <!--<li><%#= link_to 'Contact', contact_path %></li>-->
    <!--</ul>-->
  <!--</nav>-->

<!--</footer>-->

<div class="container jumbotron container_main" style=" margin-bottom: 0px; color: white; background: black;" >
  <div class="row" style="margin:0 auto; color: #f2f2f2">
    <div class="col-md-4">
    </div>
    <div class="col-md-2" >
      <div class="row">
        <div class="col-md-12">
            <h4>General</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
         <!-- Reminder -->
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= link_to t("static.privacy"), privacy_path, style: "color: inherit" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= link_to t("static.terms"), terms_and_conditions_path, style: "color: inherit" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
         <!-- Car Sharing-->
        </div>
      </div>
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-1" >
      <div class="row">
        <div class="col-md-12">
          <h4>TUMitfahrer</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
        <!--  About -->
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= link_to t("static.team"), team_path, style: "color: inherit" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= link_to t("static.contact_us"), contact_path, style: "color: inherit" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <!-- Feedback -->
        </div>
      </div>
    </div>
    <div class="col-md-4"></div>
  </div>

  <div class="row" style="margin:0 auto">
    <div class="col-md-5">
    </div>
    <div class="col-md-2"  style="text-align: center;">
      <%= link_to image_tag("logo.png", :border => 0, :style => "width: 140px"), root_path, class: "navbar-brand" %>
    </div>
    <div class="col-md-6">
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<%= javascript_include_tag "jquery.tooltipster.min.js" %>
<%= stylesheet_link_tag "tooltipster" %>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.png", :border => 0, :style => "width: 140px"), root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <div class="navbar-right">
        <% if signed_in? %>
          <form class="navbar-form" role="form">
            <%= link_to "Sign out", signout_path, method: "delete", class: "btn btn-primary", style:"height: 29px; padding-top: 2px;" %>
          </form>
        <% else %>
          <form class="navbar-form" role="form">
            <div class="form-group tooltip" title="Email or password is incorrect." style="position: relative; opacity: 0.8">
              <%= text_field_tag "session[email]", "", placeholder: "TUM Email", class: "form-control", style: "color: #c8c8c8; margin-bottom: 0px; background-color: #2B2B2B; border: medium none" %>
            </div>
            <div class="form-group">
              <%= password_field_tag "session[password]", "", placeholder: "Password", class: "form-control", style: "color: #c8c8c8; margin-bottom: 0px; background-color: #2B2B2B; border: medium none" %>
            </div>
            <button type="button" id="sign_in" class="btn btn-info" style="height: 32px; padding-top: 2px;">Sign in</button>
            <%= link_to "Sign up", "/signup", class: "btn btn-primary", style:"height: 32px; padding-top: 2px;" %>
            <%= link_to "Forgot password" ,"/password_resets/new", style:"height: 32px; padding-top: 4px; color: white;" %>
          </form>
        <% end %>
      </div>
    </div><!--/.navbar-collapse -->
    <% if signed_in? %>
        <div class="navbar-collapse collapse">
          <div class="row row-centered">
            <div class="col-md-1 col-centered" style="background: #0F3750; width: 14%; min-width: 100px; color: #beddf1; text-align: center;">
              <p><%= image_tag("NewsFeedIcon@2x.png", class: "head-button" )%><%= link_to t("static.timeline"), "/timeline", style: "color: #beddf1" %></p>
            </div>
            <div class="col-md-1 col-centered" style="background: #005c91; width: 14%; min-width: 100px; color: #beddf1; text-align: center;">
              <p><%= image_tag("campus_rides.png", class: "head-button" )%><%= link_to t("static.campus"), "/campus", style: "color: #beddf1" %></p>
            </div>
            <div class="col-md-1 col-centered" style="background: #005c91; width: 14%; min-width: 100px; color: #beddf1; text-align: center;">
              <p><%= image_tag("activity_icon.png", class: "head-button" )%><%= link_to t("static.activity"), "/activities", style: "color: #beddf1; margin-right: 5px;" %></p>
            </div>
            <div class="col-md-1 col-centered" style="background: #0076b3; width: 14%; min-width: 100px; color: #beddf1; text-align: center;">
              <p><%= image_tag("create_ride_image.png", class: "head-button" )%><%= link_to t("static.Create"), new_ride_path, style: "color: #beddf1; margin-right: 10px;" %></p>
            </div>
            <div class="col-md-1 col-centered" style="background: #0076b3; width: 14%; min-width: 100px; color: #beddf1; text-align: center;">
              <p><%= image_tag("SearchIcon.png", class: "head-button" )%><%= link_to t("static.Search"), "/search_rides", style: "color: #beddf1; margin-right: 7px;" %></p>
            </div>
            <div class="col-md-1 col-centered" style="background: #53A2d0; width: 14%; min-width: 100px; color: #beddf1; text-align: center;">
              <p><%= image_tag("my_rides.png", class: "head-button" )%><%= link_to t("static.My_rides"), "/my_rides/#{current_user.id}", style: "color: #beddf1" %></p>

            </div>
            <div class="col-md-1 col-centered" style="background: #53A2d0; width: 14%; min-width: 100px; color: #beddf1; text-align: center;">
              <p><%= image_tag("ProfileIcon.png", class: "head-button" )%><%= link_to t("static.Profile"), "/users/#{current_user.id}", style: "color: #beddf1; margin-right: 12px;" %></p>
            </div>
          </div>
        </div>
        <style>
            .row-centered {
                text-align:center;
            }
            .col-centered {
                display:inline-block;
                float:none;
                /* reset the text-align */
                text-align:left;
                /* inline-block space fix */
                margin-right:-4px;
            }
            .head-button {
                width:16px; margin-right: 4px;
            }
        </style>
    <% end %>
      </div>
    </div><!--/.navbar-collapse -->

<script type="text/javascript">
    $(document).ready(function() {
        $('.tooltip').tooltipster({
            trigger: 'custom'
        });

//        $("#sign_up").click(function(e) {
//            $('#exitpopup').css('left', (window.innerWidth/2 - $('#exitpopup').width()/2));
//            $('#exitpopup').css('top', (window.innerHeight/2 - $('#exitpopup').height()/2));
//
////            if(e.pageY <= 5) {
//                $('#exitpopup_bg').fadeIn();
//                $('#exitpopup').fadeIn();
////            }
//        });
//        $('#exitpopup_bg').click(function(){
//            $('#exitpopup_bg').fadeOut();
//            $('#exitpopup').slideUp();
//        });

        $("#sign_in").click(function() {
            $.ajax({
                type: "POST",
                url: "/sessions",
                data: { "session[email]": $("#session_email").val(), "session[password]": $("#session_password").val() },
                dataType: "JSON"
            })
            .done(function( msg ) {
                if (msg.status != "ok")
                    $('.tooltip').tooltipster('show');
                else
                    location.reload();
            });
        });

        $(window).keypress(function() {
            $('.tooltip').tooltipster('hide');
        });
    });
</script>

<!--<div style="display: none; width:100%; height:100%; position:fixed; background:#000000; opacity: .8; filter:alpha(opacity=0.8); z-index:999998;" id="exitpopup_bg"> </div>-->
<!--<div class="container" style="margin:0px auto; display:none; position:fixed; color:#ffffff; padding:20px; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; z-index:999999; background:rgb(20, 20, 20); background:rgba(0, 0, 0, 0.8);" id="exitpopup">-->
  <!--<h1>Sign Up</h1>-->
  <!--<div class="row">-->
    <!--<div class="col-xs-8 col-xs-offset-2">-->
      <!--<%#= form_for(User.new, multipart: true) do |f| %>-->
          <!--<%#= render 'shared/error_messages', object: f.object %>-->

          <!--<%#= f.label :first_name %>-->
          <!--<%#= f.text_field :first_name %>-->

          <!--<%#= f.label :last_name %>-->
          <!--<%#= f.text_field :last_name %>-->

          <!--<%#= f.label :email %>-->
          <!--<%#= f.text_field :email %>-->

          <!--<%#= f.label :department %>-->
          <!--<%#= f.text_field :department %>-->

          <!--<%#= f.label :password %>-->
          <!--<%#= f.password_field :password %>-->

          <!--<%#= f.label :password_confirmation, "Confirmation Password" %>-->
          <!--<%#= f.password_field :password_confirmation %>-->

          <!--<%#= f.label :avatar %>-->
          <!--<%#= f.file_field :avatar %>-->

          <!--<br>-->
          <!--<%#= f.submit "Create my account", class: "btn btn-large btn-primary" %>-->

      <!--<%# end %>-->
    <!--</div>-->
  <!--</div>-->
<!--</div>-->

<style>
    .navbar-collapse {
        text-align: center !important;
    }
</style>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="TUMitfahrer">
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "jumbotron", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <!--just steal some css code from ng-newsletter.com, Lukas will re-design the css-->
  <!--<link rel="stylesheet" href="http://www.ng-newsletter.com/css/site.css?cb=12">-->
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>

<!--<div class="container">-->
  <% flash.each do |key, value| %>
    <% if signed_in? %>
      <div class="alert alert-<%= key %>" style="margin-bottom: 0px; margin-top: 40px;"><%= value %></div>
    <% else %>
      <div class="alert alert-<%= key %>" style="margin-bottom: 0px;"><%= value %></div>
    <% end %>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
<!--</div>-->


</body>
</html>